/ {
    combos {
       compatibles = "zmk,combos";
combo_0 { timeout-ms = <50>; key-positions = <LT3 LM3>; bindings = <&kp LEFT_BRACKET>; };
combo_1 { timeout-ms = <50>; key-positions = <RM1 RB1>; bindings = <&kp N7>; };
combo_2 { timeout-ms = <50>; key-positions = <RM1 RB2>; bindings = <&kp UNDERSCORE>; };
combo_3 { timeout-ms = <50>; key-positions = <LM2 LT1>; bindings = <&kp AT>; };
combo_4 { timeout-ms = <50>; key-positions = <LB2 LM1>; bindings = <&kp MINUS>; };
combo_5 { timeout-ms = <50>; key-positions = <RB1 RB3>; bindings = <&kp AMPERSAND>; };
combo_6 { timeout-ms = <50>; key-positions = <RT1 RT3>; bindings = <&kp HASH>; };
combo_7 { timeout-ms = <50>; key-positions = <RM4 RB4>; bindings = <&kp N0>; };
combo_8 { timeout-ms = <50>; key-positions = <LT1 LM1>; bindings = <&kp LEFT_PARENTHESIS>; };
combo_9 { timeout-ms = <50>; key-positions = <LB3 LB1>; bindings = <&kp ASTERISK>; };
combo_10 { timeout-ms = <50>; key-positions = <LM0 LB0>; bindings = <&kp N5>; };
combo_11 { timeout-ms = <50>; key-positions = <LM1 LT2>; bindings = <&kp BACKSLASH>; };
combo_12 { timeout-ms = <50>; key-positions = <LM4 LB4>; bindings = <&kp N1>; };
combo_13 { timeout-ms = <50>; key-positions = <RM2 RT1>; bindings = <&kp PERCENT>; };
combo_14 { timeout-ms = <50>; key-positions = <LM2 LB2>; bindings = <&kp N3>; };
combo_15 { timeout-ms = <50>; key-positions = <RT2 RT3>; bindings = <&kp DOLLAR>; };
combo_16 { timeout-ms = <50>; key-positions = <LT0 LM0>; bindings = <&kp LESS_THAN>; };
combo_17 { timeout-ms = <50>; key-positions = <RM1 RT2>; bindings = <&kp PIPE>; };
combo_18 { timeout-ms = <50>; key-positions = <LT3 LT1>; bindings = <&kp TILDE>; };
combo_19 { timeout-ms = <50>; key-positions = <RT1 RM1>; bindings = <&kp RIGHT_PARENTHESIS>; };
combo_20 { timeout-ms = <50>; key-positions = <RT3 RM3>; bindings = <&kp RIGHT_BRACKET>; };
combo_21 { timeout-ms = <50>; key-positions = <LT2 LT1>; bindings = <&kp SEMICOLON>; };
combo_22 { timeout-ms = <50>; key-positions = <RT2 RM2>; bindings = <&kp RIGHT_BRACE>; };
combo_23 { timeout-ms = <50>; key-positions = <RM1 RM2 RM3>; bindings = <&sk RIGHT_SHIFT>; };
combo_24 { timeout-ms = <50>; key-positions = <RM3 RB3>; bindings = <&kp N9>; };
combo_25 { timeout-ms = <50>; key-positions = <LM1 LB1>; bindings = <&kp N4>; };
combo_26 { timeout-ms = <50>; key-positions = <RT1 RT2>; bindings = <&kp COLON>; };
combo_27 { timeout-ms = <50>; key-positions = <LM3 LM2 LM1>; bindings = <&sk LEFT_SHIFT>; };
combo_28 { timeout-ms = <50>; key-positions = <LT3 LT2>; bindings = <&kp EXCLAMATION>; };
combo_29 { timeout-ms = <50>; key-positions = <RB2 RB3>; bindings = <&kp CARET>; };
combo_30 { timeout-ms = <50>; key-positions = <LM2 LB1>; bindings = <&kp EQUAL>; };
combo_31 { timeout-ms = <50>; key-positions = <RT0 RM0>; bindings = <&kp GREATER_THAN>; };
combo_32 { timeout-ms = <50>; key-positions = <LT2 LM2>; bindings = <&kp LEFT_BRACE>; };
combo_33 { timeout-ms = <50>; key-positions = <LM3 LB3>; bindings = <&kp N2>; };
combo_34 { timeout-ms = <50>; key-positions = <RM2 RB2>; bindings = <&kp N8>; };
combo_35 { timeout-ms = <50>; key-positions = <RM2 RB1>; bindings = <&kp GRAVE>; };
combo_36 { timeout-ms = <50>; key-positions = <RM0 RB0>; bindings = <&kp N6>; };
combo_37 { timeout-ms = <50>; key-positions = <LB3 LB2>; bindings = <&kp PLUS>; };
    };
};